apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
    selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
        environment: sample
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      #  - name: mongo-key
      #  secret:
      #    defaultMode: 0400
      #    secretName: mongo-key
        - name: mongo-pv-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
         #   - name: mongo-key
         #     mountPath: "/etc/secrets-volume"
          #    readOnly: true
            - name: mongo-pv-storage
              mountPath: /data/db  
          env:           
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-key
                  key: password
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
