apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
        environment: sample
    spec:
      terminationGracePeriodSeconds: 10
      volumes:    
        - name: mongo-pv-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
      containers:
        - name: mongodb
          image: mongo        
          ports:
            - containerPort: 27017
          volumeMounts:         
            - name: mongo-pv-storage
              mountPath: /data/db 
